-- =====================================================================
-- Martinho: tabelas do sistema (versão Next.js + Supabase)
-- =====================================================================
--
-- Multi-tenant: cada barbearia é um "inquilino". Toda tabela de dados tem
-- a coluna barbearia_id, e as políticas de RLS (próxima migration) só
-- deixam cada usuário ver e alterar as linhas da própria barbearia.
--
-- Os nomes das tabelas não colidem com os do Django (contas_*, cadastros_*,
-- agenda_*), então as duas versões convivem no mesmo banco até a troca.
--
-- Regras que no Django ficavam no Python e aqui ficam no próprio banco:
--
-- * "Cliente, barbeiro e serviço precisam ser da mesma barbearia do
--   agendamento" (mesma_barbearia no Django) -> chaves estrangeiras
--   compostas: (barbearia_id, cliente_id) aponta para (barbearia_id, id)
--   do cliente. Se o cliente for de outra barbearia, o par não existe e o
--   banco recusa a gravação.
--
-- * "Dois agendamentos do mesmo barbeiro não podem se sobrepor"
--   (select_for_update + verificação no save) -> exclusion constraint.
--   O próprio Postgres garante, mesmo com dois pedidos chegando ao mesmo
--   tempo: o segundo falha com o erro 23P01.
-- =====================================================================

create schema if not exists extensions;
-- btree_gist permite combinar "mesmo barbeiro" (=) com "horários se
-- sobrepõem" (&&) numa única regra de exclusão.
create extension if not exists btree_gist with schema extensions;

-- Funções internas (não ficam expostas na API do Supabase, que só publica
-- o schema public).
create schema if not exists privado;

-- Fuso usado para transformar "dia + hora local" em instante (timestamptz).
create function privado.fuso() returns text
language sql immutable as $$ select 'America/Sao_Paulo' $$;

-- Mantém atualizado_em sempre correto, em qualquer UPDATE.
create function privado.tocar_atualizado_em() returns trigger
language plpgsql as $$
begin
  new.atualizado_em := now();
  return new;
end $$;

-- ---------------------------------------------------------------------
-- Telefones (mesma regra de lib/telefones.ts)
-- ---------------------------------------------------------------------
-- Dígitos com o código do Brasil (55), ou '' se o número estiver
-- incompleto. Telefones com DDD (10 ou 11 dígitos) ganham o 55 na frente.
-- "immutable" permite usar a função numa coluna gerada e num índice.
create function public.formato_internacional(telefone text) returns text
language sql immutable as $$
  select case
    when length(d) in (10, 11) then '55' || d
    when length(d) >= 12 then d
    else ''
  end
  from (select regexp_replace(coalesce(telefone, ''), '\D', '', 'g') as d) as x
$$;

-- ---------------------------------------------------------------------
-- Barbearias (os inquilinos)
-- ---------------------------------------------------------------------
create table public.barbearias (
  id bigint generated by default as identity primary key,
  nome text not null check (length(trim(nome)) between 1 and 120),
  -- Parte do endereço da página de agendamento: /agendar/<slug>
  slug text not null unique
    check (length(slug) <= 60 and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  -- Aparece na página de agendamento para contato.
  telefone text not null default '' check (length(telefone) <= 20),
  endereco text not null default '' check (length(endereco) <= 255),
  agendamento_online boolean not null default true,
  criado_em timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Perfis: quem faz login. O login em si (e-mail e senha) fica no
-- Supabase Auth (tabela auth.users); aqui ficam a barbearia e o papel.
-- ---------------------------------------------------------------------
create table public.perfis (
  id uuid primary key references auth.users (id) on delete cascade,
  -- Vazio só para o superadmin (você, administrando o sistema).
  barbearia_id bigint references public.barbearias (id) on delete restrict,
  nome text not null default '' check (length(nome) <= 120),
  papel text not null default 'dono' check (papel in ('dono', 'barbeiro')),
  -- Superadmin: cria barbearias e logins pelo painel /admin.
  superadmin boolean not null default false,
  criado_em timestamptz not null default now(),
  -- Alvo das chaves compostas (ver barbeiros.usuario_id).
  unique (barbearia_id, id)
);

-- ---------------------------------------------------------------------
-- Barbeiros
-- ---------------------------------------------------------------------
create table public.barbeiros (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id) on delete restrict,
  nome text not null check (length(trim(nome)) between 1 and 120),
  telefone text not null default '' check (length(telefone) <= 20),
  -- Barbeiro desativado some da agenda, mas continua no histórico.
  ativo boolean not null default true,
  -- Opcional: um barbeiro pode existir sem ter login no sistema.
  usuario_id uuid unique,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (barbearia_id, id),
  -- O login ligado ao barbeiro precisa ser da mesma barbearia. Se o login
  -- for apagado, só usuario_id vira nulo (o barbeiro continua).
  foreign key (barbearia_id, usuario_id) references public.perfis (barbearia_id, id)
    on delete set null (usuario_id)
);

-- ---------------------------------------------------------------------
-- Serviços
-- ---------------------------------------------------------------------
create table public.servicos (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id) on delete restrict,
  nome text not null check (length(trim(nome)) between 1 and 120),
  -- numeric em vez de float: float guarda 0.1 como 0.1000000000000000055…
  -- e isso gera centavos errados em somas de dinheiro.
  preco numeric(8, 2) not null check (preco >= 0),
  -- A duração define o fim do agendamento, usado para detectar conflitos.
  duracao_minutos smallint not null default 30 check (duracao_minutos >= 5),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (barbearia_id, id),
  constraint servico_nome_unico_por_barbearia unique (barbearia_id, nome)
);

-- ---------------------------------------------------------------------
-- Clientes
-- ---------------------------------------------------------------------
create table public.clientes (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id) on delete restrict,
  nome text not null check (length(trim(nome)) between 1 and 120),
  telefone text not null default '' check (length(telefone) <= 20),
  -- Telefone normalizado (5511987654321), calculado pelo banco. Serve para
  -- reconhecer o cliente pelo telefone, ignorando a formatação.
  telefone_whatsapp text generated always as (public.formato_internacional(telefone)) stored,
  email text not null default '' check (length(email) <= 254),
  data_nascimento date,
  endereco text not null default '' check (length(endereco) <= 255),
  observacoes text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (barbearia_id, id)
);
create index clientes_barbearia_nome_idx on public.clientes (barbearia_id, nome);
create index clientes_barbearia_telefone_idx on public.clientes (barbearia_id, telefone_whatsapp);

-- ---------------------------------------------------------------------
-- Horários de trabalho: um turno num dia da semana. Um dia pode ter dois
-- turnos (09:00-12:00 e 13:00-19:00); o intervalo é o almoço.
-- ---------------------------------------------------------------------
create table public.horarios_trabalho (
  id bigint generated by default as identity primary key,
  -- barbearia_id repetido aqui (já dá para chegar nele pelo barbeiro) para
  -- a regra de RLS ser uma comparação simples, sem consultar outra tabela.
  barbearia_id bigint not null,
  barbeiro_id bigint not null,
  -- 0 = segunda ... 6 = domingo (mesma numeração do Django).
  dia_semana smallint not null check (dia_semana between 0 and 6),
  inicio time not null,
  fim time not null,
  constraint horario_fim_depois_do_inicio check (fim > inicio),
  foreign key (barbearia_id, barbeiro_id) references public.barbeiros (barbearia_id, id) on delete cascade
);
create index horarios_barbeiro_idx on public.horarios_trabalho (barbeiro_id, dia_semana);

-- ---------------------------------------------------------------------
-- Ausências: folga, férias, falta, consulta.
-- Sem horário: vale para os dias inteiros de data_inicio a data_fim.
-- Com horário: só aquele trecho de um único dia ("saiu às 15:00").
-- ---------------------------------------------------------------------
create table public.ausencias (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null,
  barbeiro_id bigint not null,
  data_inicio date not null,
  data_fim date not null,
  hora_inicio time,
  hora_fim time,
  motivo text not null default '' check (length(motivo) <= 80),
  criado_em timestamptz not null default now(),
  constraint ausencia_fim_depois_do_inicio check (data_fim >= data_inicio),
  -- Horário: os dois preenchidos (fim depois do início, num dia só) ou nenhum.
  constraint ausencia_horario_completo check (
    (hora_inicio is null and hora_fim is null)
    or (hora_inicio is not null and hora_fim is not null and hora_fim > hora_inicio and data_inicio = data_fim)
  ),
  foreign key (barbearia_id, barbeiro_id) references public.barbeiros (barbearia_id, id) on delete cascade
);
create index ausencias_barbeiro_datas_idx on public.ausencias (barbeiro_id, data_inicio, data_fim);

-- ---------------------------------------------------------------------
-- Agendamentos
-- ---------------------------------------------------------------------
create table public.agendamentos (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id) on delete restrict,
  cliente_id bigint not null,
  barbeiro_id bigint not null,
  servico_id bigint not null,
  inicio timestamptz not null,
  -- Calculado pela duração do serviço (gatilho abaixo) se vier vazio.
  fim timestamptz not null,
  status text not null default 'agendado'
    check (status in ('agendado', 'concluido', 'cancelado', 'faltou')),
  observacoes text not null default '',
  -- Código da página de confirmação do cliente. Aleatório, para ninguém ver
  -- o horário de outra pessoa trocando um número no endereço.
  codigo_publico uuid not null default gen_random_uuid() unique,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (barbearia_id, id),
  constraint agendamento_fim_depois_do_inicio check (fim > inicio),
  -- Sem "on delete": o banco recusa apagar um cliente, barbeiro ou serviço
  -- que tem agendamentos (o PROTECT do Django). O caminho é desativar.
  foreign key (barbearia_id, cliente_id) references public.clientes (barbearia_id, id),
  foreign key (barbearia_id, barbeiro_id) references public.barbeiros (barbearia_id, id),
  foreign key (barbearia_id, servico_id) references public.servicos (barbearia_id, id),
  -- Conflito de horário. tstzrange(inicio, fim) é o intervalo [inicio, fim):
  -- inclui o início e exclui o fim, por isso 14:00-14:30 e 14:30-15:00 não
  -- conflitam. Cancelados não ocupam o horário (cláusula where).
  constraint agendamento_sem_conflito exclude using gist (
    barbeiro_id with =,
    tstzrange(inicio, fim) with &&
  ) where (status <> 'cancelado')
);
create index agendamentos_barbearia_inicio_idx on public.agendamentos (barbearia_id, inicio);

-- O fim sai da duração do serviço. Na remarcação (mudou o início ou o
-- serviço) o fim é recalculado, como no Django.
create function privado.calcular_fim_agendamento() returns trigger
language plpgsql as $$
begin
  if new.fim is null
     or (tg_op = 'UPDATE' and new.fim is not distinct from old.fim
         and (new.inicio <> old.inicio or new.servico_id <> old.servico_id)) then
    select new.inicio + make_interval(mins => s.duracao_minutos)
      into new.fim
      from public.servicos s
     where s.id = new.servico_id;
  end if;
  return new;
end $$;

create trigger calcular_fim before insert or update on public.agendamentos
  for each row execute function privado.calcular_fim_agendamento();

-- ---------------------------------------------------------------------
-- Atendimentos: o histórico do cliente. Nasce ao concluir um agendamento
-- ou é registrado direto, para quem chega sem hora marcada.
-- ---------------------------------------------------------------------
create table public.atendimentos (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id) on delete restrict,
  cliente_id bigint not null,
  -- Se o barbeiro for apagado, o histórico continua (vira nulo).
  barbeiro_id bigint,
  agendamento_id bigint unique,
  data date not null default (now() at time zone 'America/Sao_Paulo')::date,
  observacoes text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (barbearia_id, id),
  foreign key (barbearia_id, cliente_id) references public.clientes (barbearia_id, id),
  foreign key (barbearia_id, barbeiro_id) references public.barbeiros (barbearia_id, id)
    on delete set null (barbeiro_id),
  foreign key (barbearia_id, agendamento_id) references public.agendamentos (barbearia_id, id)
    on delete set null (agendamento_id)
);
create index atendimentos_barbearia_data_idx on public.atendimentos (barbearia_id, data);
create index atendimentos_cliente_idx on public.atendimentos (cliente_id, data);

-- ---------------------------------------------------------------------
-- Itens do atendimento. Descrição e valor são copiados do serviço no
-- momento do atendimento: se o preço subir, o histórico mostra o valor
-- que o cliente realmente pagou.
-- ---------------------------------------------------------------------
create table public.itens_atendimento (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null,
  atendimento_id bigint not null,
  servico_id bigint,
  descricao text not null check (length(trim(descricao)) between 1 and 120),
  valor numeric(8, 2) not null check (valor >= 0),
  foreign key (barbearia_id, atendimento_id) references public.atendimentos (barbearia_id, id) on delete cascade,
  foreign key (barbearia_id, servico_id) references public.servicos (barbearia_id, id) on delete set null (servico_id)
);
create index itens_atendimento_idx on public.itens_atendimento (atendimento_id);

create function privado.preencher_item_do_servico() returns trigger
language plpgsql as $$
begin
  if new.servico_id is not null and (new.descricao is null or new.valor is null) then
    select coalesce(new.descricao, s.nome), coalesce(new.valor, s.preco)
      into new.descricao, new.valor
      from public.servicos s
     where s.id = new.servico_id;
  end if;
  return new;
end $$;

create trigger preencher_do_servico before insert or update on public.itens_atendimento
  for each row execute function privado.preencher_item_do_servico();

-- ---------------------------------------------------------------------
-- Aparelhos inscritos nas notificações push (Web Push / VAPID).
-- ---------------------------------------------------------------------
create table public.inscricoes_push (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.perfis (id) on delete cascade,
  endpoint text not null unique check (endpoint like 'https://%' and length(endpoint) <= 500),
  p256dh text not null check (length(p256dh) <= 200),
  auth text not null check (length(auth) <= 100),
  navegador text not null default '' check (length(navegador) <= 200),
  criado_em timestamptz not null default now()
);

-- atualizado_em automático
create trigger tocar before update on public.barbeiros for each row execute function privado.tocar_atualizado_em();
create trigger tocar before update on public.servicos for each row execute function privado.tocar_atualizado_em();
create trigger tocar before update on public.clientes for each row execute function privado.tocar_atualizado_em();
create trigger tocar before update on public.agendamentos for each row execute function privado.tocar_atualizado_em();
create trigger tocar before update on public.atendimentos for each row execute function privado.tocar_atualizado_em();
