# Generated by Django 6.1.1 on 2026-09-30 19:20

from django.db import migrations, models
from django.utils.text import slugify


def preencher_slugs(apps, schema_editor):
    # Barbearias que já existiam ganham um endereço a partir do nome.
    Barbearia = apps.get_model('contas', 'Barbearia')
    usados = set()
    for barbearia in Barbearia.objects.order_by('pk'):
        base = slugify(barbearia.nome)[:50] or 'barbearia'
        slug, n = base, 2
        while slug in usados:
            slug, n = f'{base}-{n}', n + 1
        usados.add(slug)
        barbearia.slug = slug
        barbearia.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='agendamento_online',
            field=models.BooleanField(default=True, help_text='Permite que clientes agendem pela página pública.', verbose_name='agendamento online'),
        ),
        # Em três passos, para funcionar com barbearias já cadastradas:
        # 1) cria o campo sem a regra de único e sem índice; 2) preenche;
        # 3) liga a regra de único, que também cria o índice.
        # O db_index=False do passo 1 evita um erro do Django no PostgreSQL:
        # o SlugField já nasce com índice (mais um índice "_like" para buscas
        # de texto), e o passo 3 tentaria criar o "_like" de novo.
        migrations.AddField(
            model_name='barbearia',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=60, verbose_name='endereço da página'),
        ),
        migrations.RunPython(preencher_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='barbearia',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='endereço da página'),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='telefone',
            field=models.CharField(blank=True, help_text='Aparece na página de agendamento para contato.', max_length=20),
        ),
    ]
