# Generated by Django 6.1.1 on 2026-09-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_barbearia_slug_agendamento_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('navegador', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aparelho com avisos',
                'verbose_name_plural': 'aparelhos com avisos',
            },
        ),
    ]
