# Generated by Django 6.1.1 on 2026-09-30 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('faltou', 'Faltou')], default='agendado', max_length=10)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cadastros.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cadastros.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cadastros.servico', verbose_name='serviço')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='agenda.agendamento')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.barbearia')),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='cadastros.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='cadastros.cliente')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=120, verbose_name='descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agenda.atendimento')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servico', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'item do atendimento',
                'verbose_name_plural': 'itens do atendimento',
            },
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['barbearia', 'inicio'], name='agenda_agen_barbear_fff6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['barbeiro', 'inicio'], name='agenda_agen_barbeir_d80085_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendamento_fim_depois_do_inicio'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['barbearia', 'cliente', 'data'], name='agenda_aten_barbear_3a6c68_idx'),
        ),
    ]
