# Generated by Django 6.1.1 on 2026-09-30 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.barbearia')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbeiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.barbearia')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['barbearia', 'nome'], name='cadastros_c_barbear_659bb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço')),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='duração (minutos)')),
                ('ativo', models.BooleanField(default=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.barbearia')),
            ],
            options={
                'verbose_name': 'serviço',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('barbearia', 'nome'), name='servico_nome_unico_por_barbearia')],
            },
        ),
    ]
