# Generated by Django 6.1.1 on 2026-09-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='de')),
                ('data_fim', models.DateField(verbose_name='até')),
                ('motivo', models.CharField(blank=True, max_length=80)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='cadastros.barbeiro')),
            ],
            options={
                'verbose_name': 'folga ou férias',
                'verbose_name_plural': 'folgas e férias',
                'ordering': ['data_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='bloqueio_fim_depois_do_inicio')],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('inicio', models.TimeField(verbose_name='início')),
                ('fim', models.TimeField()),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cadastros.barbeiro')),
            ],
            options={
                'verbose_name': 'horário de trabalho',
                'verbose_name_plural': 'horários de trabalho',
                'ordering': ['dia_semana', 'inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='horario_fim_depois_do_inicio')],
            },
        ),
    ]
