# Generated by Django 6.1.1 on 2026-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_bloqueio_horariotrabalho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueio',
            options={'ordering': ['data_inicio', 'hora_inicio'], 'verbose_name': 'ausência', 'verbose_name_plural': 'ausências (folgas, férias, faltas)'},
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='às'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='das'),
        ),
        migrations.AddConstraint(
            model_name='bloqueio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hora_fim__isnull', True), ('hora_inicio__isnull', True)), models.Q(('hora_fim__gt', models.F('hora_inicio')), ('hora_fim__isnull', False), ('hora_inicio__isnull', False)), _connector='OR'), name='bloqueio_horario_completo'),
        ),
    ]
